# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/TheOtherUniverse"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/maksmerkurev"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "telegram"
name = "Telegram"
url = "https://t.me/math_and_code"

[social.params]
icon = "brand-telegram"
